# Generated by Django 5.0.6 on 2024-10-12 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cultural_sites',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='places_to_visit',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='title',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_cost',
        ),
        migrations.AddField(
            model_name='trip',
            name='convenience_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='Неизвестно', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_images/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='population_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='safety_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='vegetation_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
